"""
gc_agent.py — Phase 6: Monitoring & Feedback (Garbage Collection Agent)

Runs nightly. Reads decision_log, conflict_log, override_log, and
current policy files. Produces PRs (as markdown files) that fix:
  - Stale policy rules
  - Recurring conflict patterns → conflict_policy.yaml updates
  - Human overrides → new policy rules that encode that judgment
  - Stale documentation → updated docs

This is the self-improvement engine of the harness.
When the GC agent runs and produces zero PRs, the harness is healthy.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

from harness.agents.base_agent import AgentResult, BaseAgent
from harness.logs.conflict_log import ConflictLog
from harness.logs.decision_log import DecisionLog
from harness.logs.conflict_log import OverrideLog


class GCAgent(BaseAgent):
    phase = "monitoring"

    def run(self, input_data: dict) -> AgentResult:
        # Load all signal sources
        decision_log = DecisionLog(self.config.logs_dir)
        conflict_log = ConflictLog(self.config.logs_dir)
        override_log = OverrideLog(self.config.logs_dir)

        decisions = decision_log.read_all()
        conflicts = conflict_log.read_all()
        overrides = override_log.read_all()
        failures = decision_log.read_failures()
        needs_human = decision_log.read_needs_human()

        context = self.build_context(
            extra_docs=["requirements.md", "architecture.md", "quality.md"]
        )

        prompt = f"""
{context}

=== TASK ===
You are the GCAgent — the nightly garbage collection agent for the SDLC harness.
Your job is to find drift, inconsistencies, and missing rules, then propose
precise harness fixes as pull request descriptions.

=== SIGNALS ===

Recent decisions ({len(decisions)} total):
{json.dumps(decisions[-20:], indent=2)}

Recent conflicts ({len(conflicts)} total):
{json.dumps(conflicts[-10:], indent=2)}

Human overrides ({len(overrides)} total):
{json.dumps(overrides[-10:], indent=2)}

Failures: {len(failures)}
Needs-human: {len(needs_human)}

=== WHAT TO LOOK FOR ===

1. STALE POLICY RULES — rules in policy.yaml that no longer reflect
   what the decisions show. Propose updated rule text.

2. CONFLICT PATTERNS — agent pairs that repeatedly conflict on the same
   type of input. Propose a new conflict_policy.yaml entry.

3. OVERRIDE ENCODING — human overrides that reveal a rule the harness
   is missing. Propose the exact policy rule that would have produced
   the correct decision automatically.

4. STALE DOCS — sections of requirements.md or architecture.md that
   contradict the current decision patterns.

5. QUALITY DRIFT — agents whose confidence has been declining.

Return JSON with keys:
1. "prs" — list of proposed PRs, each:
   {{
     "pr_id": str,
     "title": str,
     "target_file": str,   (e.g. "policies/policy.yaml")
     "change_type": "add"|"update"|"delete",
     "current_content": str,   (relevant excerpt of current content)
     "proposed_content": str,  (exact replacement)
     "rationale": str,
     "signal_source": "conflict_log"|"override_log"|"decision_log"|"quality"
   }}
2. "quality_md_update" — updated content for docs/quality.md
3. "summary" — 2-3 sentence summary of what the GC agent found
4. "harness_health_score" — float 0.0-1.0 (1.0 = no drift detected)

Return ONLY valid JSON.
"""
        try:
            response = self._call_llm(prompt)
            parsed = json.loads(response)

            prs = parsed.get("prs", [])

            # Write each proposed PR as a markdown file
            pr_dir = self.config.repo_root / ".harness" / "proposed_prs"
            pr_dir.mkdir(parents=True, exist_ok=True)
            timestamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M")
            pr_paths = []

            for pr in prs:
                pr_filename = f"{timestamp}_{pr['pr_id']}.md"
                pr_path = pr_dir / pr_filename
                pr_content = f"""# PR: {pr['title']}

**Target file:** `{pr['target_file']}`
**Change type:** {pr['change_type']}
**Signal source:** {pr['signal_source']}
**Rationale:** {pr['rationale']}

## Current content
```
{pr.get('current_content', '(new)')}
```

## Proposed content
```
{pr['proposed_content']}
```

---
*Generated by GCAgent at {timestamp} UTC. Requires human review before merge.*
"""
                pr_path.write_text(pr_content)
                pr_paths.append(str(pr_path))

            # Update quality.md
            if parsed.get("quality_md_update"):
                self.write_artifact("quality.md", parsed["quality_md_update"])

            health = float(parsed.get("harness_health_score", 1.0))
            status = "pass" if health >= 0.7 else "needs_human"

            return AgentResult(
                agent_name=self.name,
                phase=self.phase,
                status=status,
                output={
                    "prs_proposed": len(prs),
                    "harness_health_score": health,
                    "summary": parsed.get("summary", ""),
                    "signals_read": {
                        "decisions": len(decisions),
                        "conflicts": len(conflicts),
                        "overrides": len(overrides),
                    },
                },
                confidence=health,
                artifacts_produced=pr_paths + ["docs/quality.md"],
                flags=[f"pr_proposed: {pr['pr_id']}" for pr in prs],
            )

        except Exception as exc:
            return AgentResult(
                agent_name=self.name, phase=self.phase, status="fail",
                output={"error": str(exc)}, confidence=0.0, flags=["llm_call_failed"],
            )
