"""
action_runner.py — ActionRunner

Executes corrective actions decided by the LogMonitorAgent.
All actions are tiered — never takes autonomous destructive action.

Actions (in order of severity):
  log_only        — record to harness decision log, no intervention
  alert_human     — write to human review queue (.harness/alerts/)
  open_pr         — generate a fix PR (like GC agent) in .harness/proposed_prs/
  trigger_rollback — call RollbackAgent with synthesised metrics

The action to take for each error pattern is defined in monitoring_rules.yaml.
Changing what the harness does = editing that YAML file, not touching code.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from harness.config import HarnessConfig
    from harness.monitoring.log_event import LogWindow


VALID_ACTIONS = {"log_only", "alert_human", "open_pr", "trigger_rollback"}


@dataclass
class MonitoringDecision:
    """The structured output of the LogMonitorAgent."""
    action: str                         # one of VALID_ACTIONS
    severity: str                       # "low" | "medium" | "high" | "critical"
    summary: str                        # 1-2 sentence human-readable summary
    root_cause: str                     # agent's best guess at root cause
    matched_rules: list[str]            # rule IDs from monitoring_rules.yaml that fired
    proposed_fix: str = ""             # for open_pr: what the fix should do
    rollback_reason: str = ""          # for trigger_rollback: why rollback is warranted
    confidence: float = 0.0
    flags: list[str] = field(default_factory=list)
    timestamp: str = field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )

    def to_dict(self) -> dict:
        return {
            "timestamp": self.timestamp,
            "action": self.action,
            "severity": self.severity,
            "summary": self.summary,
            "root_cause": self.root_cause,
            "matched_rules": self.matched_rules,
            "proposed_fix": self.proposed_fix,
            "rollback_reason": self.rollback_reason,
            "confidence": self.confidence,
            "flags": self.flags,
        }


class ActionRunner:
    """
    Executes the corrective action from a MonitoringDecision.

    Called by the LogMonitorAgent after analysis:
        runner = ActionRunner(config)
        runner.execute(decision, window)
    """

    def __init__(self, config: "HarnessConfig"):
        self.config = config
        self._alerts_dir = config.repo_root / ".harness" / "alerts"
        self._prs_dir = config.repo_root / ".harness" / "proposed_prs"
        self._monitoring_log = config.logs_dir / "monitoring_log.jsonl"
        self._alerts_dir.mkdir(parents=True, exist_ok=True)
        self._prs_dir.mkdir(parents=True, exist_ok=True)

    def execute(self, decision: MonitoringDecision, window: "LogWindow") -> None:
        """Dispatch to the appropriate action handler."""
        action = decision.action
        if action not in VALID_ACTIONS:
            print(f"  ⚠ Unknown action '{action}' — defaulting to log_only")
            action = "log_only"

        self._log_decision(decision, window)

        if action == "log_only":
            self._log_only(decision)
        elif action == "alert_human":
            self._alert_human(decision, window)
        elif action == "open_pr":
            self._open_pr(decision, window)
        elif action == "trigger_rollback":
            self._trigger_rollback(decision, window)

    # ------------------------------------------------------------------
    # Action handlers
    # ------------------------------------------------------------------

    def _log_only(self, decision: MonitoringDecision) -> None:
        icon = {"low": "ℹ", "medium": "⚠", "high": "🔶", "critical": "🔴"}.get(
            decision.severity, "ℹ"
        )
        print(f"  {icon} LOG_ONLY [{decision.severity.upper()}]: {decision.summary}")

    def _alert_human(self, decision: MonitoringDecision, window: "LogWindow") -> None:
        ts = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
        alert_path = self._alerts_dir / f"{ts}_{decision.severity}.md"

        content = f"""# Alert — {decision.severity.upper()}
**Time:** {decision.timestamp}
**Severity:** {decision.severity}
**Summary:** {decision.summary}

## Root cause
{decision.root_cause}

## Matched rules
{chr(10).join(f'- {r}' for r in decision.matched_rules) or '- (none)'}

## Log window
{window.summary()}

## Sample errors
{chr(10).join(f'- [{e.level.value}] {e.message[:200]}' for e in window.errors_and_above()[:10])}

---
*Generated by LogMonitorAgent. Requires human review.*
"""
        alert_path.write_text(content)
        print(f"  🔔 ALERT_HUMAN: {alert_path.name} — {decision.summary}")

    def _open_pr(self, decision: MonitoringDecision, window: "LogWindow") -> None:
        ts = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
        pr_id = f"MON_{ts}"
        pr_path = self._prs_dir / f"{pr_id}.md"

        content = f"""# PR: {decision.summary}

**Source:** LogMonitorAgent
**Severity:** {decision.severity}
**Matched rules:** {', '.join(decision.matched_rules) or 'none'}
**Confidence:** {decision.confidence:.2f}

## Root cause analysis
{decision.root_cause}

## Proposed fix
{decision.proposed_fix or '(No specific fix proposed — review log window below)'}

## Log window context
{window.summary()}

### Sample errors triggering this PR
{chr(10).join(f'```{chr(10)}{e.message}{chr(10)}```' for e in window.errors_and_above()[:5])}

---
*Generated by LogMonitorAgent at {decision.timestamp}. Requires human review before merge.*
"""
        pr_path.write_text(content)
        print(f"  📋 OPEN_PR: {pr_path.name} — {decision.proposed_fix[:80] if decision.proposed_fix else decision.summary}")

    def _trigger_rollback(self, decision: MonitoringDecision, window: "LogWindow") -> None:
        print(f"  🔴 TRIGGER_ROLLBACK: {decision.rollback_reason}")

        # Build synthetic metrics from the log window for RollbackAgent
        error_rate = window.error_rate
        synthetic_metrics = {
            "decision_quality": max(0.0, 1.0 - error_rate),
            "agent_failure_rate": error_rate,
            "needs_human_rate": 0.0,
            "latency_p95_seconds": 0.0,
            "average_confidence": 0.5,
            "sample_size": window.total_count,
            "_monitoring_triggered": True,
            "_rollback_reason": decision.rollback_reason,
        }

        try:
            from harness.agents.release_agent import RollbackAgent
            rollback_agent = RollbackAgent(self.config)
            result = rollback_agent.execute(synthetic_metrics)

            if result.output.get("rollback_triggered"):
                print(f"  ✓ Rollback triggered: {result.output.get('threshold_breaches')}")
            else:
                print(f"  ⚠ Rollback NOT triggered — thresholds not breached by synthetic metrics")
                # Escalate to alert_human instead
                self._alert_human(decision, window)

        except Exception as exc:
            print(f"  ✗ RollbackAgent call failed: {exc} — escalating to alert_human")
            self._alert_human(decision, window)

    # ------------------------------------------------------------------
    # Logging
    # ------------------------------------------------------------------

    def _log_decision(self, decision: MonitoringDecision, window: "LogWindow") -> None:
        entry = {
            **decision.to_dict(),
            "window_summary": window.summary(),
            "error_rate": window.error_rate,
            "total_events": window.total_count,
        }
        with self._monitoring_log.open("a") as f:
            f.write(json.dumps(entry) + "\n")
